# Generated by Django 5.1.7 on 2025-03-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('mobilenumber', models.CharField(max_length=15)),
                ('preferred_time', models.TimeField()),
                ('procedure', models.TextField()),
            ],
        ),
    ]
