# Generated by Django 5.1.7 on 2025-03-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='preferred_time',
        ),
    ]
