# Generated by Django 5.1.7 on 2025-03-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_user_preferred_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_time',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
